[package]
name = "msgtausch-routing"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
compio.workspace = true
futures-util.workspace = true
lru.workspace = true
msgtausch-config = { path = "../msgtausch-config" }
msgtausch-policy = { path = "../msgtausch-policy" }
msgtausch-resolver = { path = "../msgtausch-resolver" }
tracing.workspace = true
